package typesafe4s

import java.util.concurrent.TimeUnit

import scala.concurrent.duration.*

import munit.ScalaCheckSuite
import org.scalacheck.Gen
import org.scalacheck.Prop.{classify, forAll}

// ============================================================================
// TEST ORACLE — spec: error-model (change: add-typesafe4s-sdk, spec 1/8)
//
// Written from the spec and the Gate-1 contract BEFORE any implementation.
// In-package so the oracle can exercise the SDK-internal surface
// (`private[typesafe4s]` fromResponse and member constructors); the
// outside-SDK negatives live in outside/ErrorModelCompileNegativeSuite.
//
// Deferred rows (Gate-0 decisions, 2026-09-17):
//   * "a successful call also carries its trace" — AnswerSet carries the
//     requestId; the success row lands with spec 3 (question-model)
//   * "no credential can be resolved" construction proof — spec 7
//   * "reading an answer that was never asked" no-request proof — spec 3
// ============================================================================
class ErrorModelProperties extends ScalaCheckSuite {

  // --------------------------------------------------------------------------
  // Generators — constructive (scalacheck classify is informational only;
  // interesting cases are reached by construction, never by rare draws)
  // --------------------------------------------------------------------------

  /**
    * One documented refusal class: its kind label, a status inside it, and the member it must map to.
    */
  private case class RefusalCase(kind: String, status: Int, member: String)

  // spec: error-model — Property: Every documented refusal maps to exactly one member
  // genRefusal — the enumerated documented refusals, each reached on a short run
  private val genRefusalCase: Gen[RefusalCase] = Gen.oneOf(
    Gen.const(RefusalCase("malformed", 400, "BadRequest")),
    Gen.const(RefusalCase("unauthenticated", 401, "Authentication")),
    Gen.const(RefusalCase("forbidden", 403, "PermissionDenied")),
    Gen.const(RefusalCase("unknown", 404, "NotFound")),
    Gen.const(RefusalCase("unprocessable", 422, "UnprocessableEntity")),
    Gen.const(RefusalCase("too-many-requests", 429, "RateLimit")),
    Gen.const(RefusalCase("overloaded", 529, "Overloaded")),
    // the general service-fault range — 5xx minus 529, drawn constructively
    Gen.oneOf(Gen.choose(500, 528), Gen.choose(530, 599)).map(s => RefusalCase("service-fault", s, "InternalServer"))
  )

  private val genBody: Gen[String] = Gen.asciiPrintableStr

  // header names are alphanumeric-only, so a stray `x-typesafe-request-id`
  // can never be generated by accident — the trace cases are controlled
  private val genHeaderName: Gen[String]              = Gen.nonEmptyListOf(Gen.alphaNumChar).map(_.mkString)
  private val genHeaders: Gen[List[(String, String)]] =
    Gen.listOf(genHeaderName.flatMap(n => Gen.asciiPrintableStr.map(v => (n, v))))

  private val genRefusal: Gen[(RefusalCase, List[(String, String)], String)] =
    genRefusalCase.flatMap(rc => Gen.zip(genHeaders, genBody).map { case (hs, b) => (rc, hs, b) })

  // spec: error-model — Property: A trace is carried through unchanged or reported absent
  // genOutcome — trace header drawn present / absent / present-but-empty by construction
  private val genTraceCase: Gen[Option[String]] = Gen.oneOf(
    Gen.const(None),                                                   // header absent
    Gen.nonEmptyListOf(Gen.alphaNumChar).map(cs => Some(cs.mkString)), // present, non-blank
    Gen.oneOf("", "   ", "\t").map(Some(_))                            // present but blank
  )

  private val genLimit: Gen[FiniteDuration] = Gen.choose(1L, 86_400_000L).map(_.millis)
  private val genCause: Gen[Throwable]      = Gen.asciiPrintableStr.map(msg => new RuntimeException(msg))

  // the service names its delay in Retry-After (seconds) or retry-after-ms (millis);
  // header names MUST-CONFIRM per registry (task 12.3)
  private val genRetryAfterCase: Gen[(List[(String, String)], Option[FiniteDuration])] = Gen.oneOf(
    Gen.const((List.empty[(String, String)], None)), // unnamed
    Gen.choose(0L, 86_400L).map(s => (List("Retry-After" -> s.toString), Some(FiniteDuration(s, TimeUnit.SECONDS)))),
    Gen.choose(0L, 86_400_000L).map(ms => (List("retry-after-ms" -> ms.toString), Some(FiniteDuration(ms, TimeUnit.MILLISECONDS)))),
    Gen.const((List("Retry-After" -> ""), None)), // blank = unnamed
    Gen.const((List("Retry-After" -> "soon"), None)), // unparseable = unnamed
    // Ring-8 edge cases: beyond FiniteDuration's ±(2^63-1)ns range, and negative
    // — neither is a delay the service could have named, so both are unnamed
    Gen.choose(9_223_372_037L, Long.MaxValue).map(s => (List("Retry-After" -> s.toString), None)),
    Gen.choose(9_223_372_036_855L, Long.MaxValue).map(ms => (List("retry-after-ms" -> ms.toString), None)),
    Gen.choose(Long.MinValue + 1, -1L).map(s => (List("Retry-After" -> s.toString), None))
  )

  // --------------------------------------------------------------------------
  // Requirement: Every failure belongs to one closed family
  // --------------------------------------------------------------------------

  // spec: error-model — Scenario: Distinguishing every member suffices
  // This match has no catch-all; it only compiles because the family is closed
  // and complete. `memberName` is the executable witness for the scenario.
  private def memberName(e: TypesafeException): String = e match {
    case _: TypesafeException.BadRequest           => "BadRequest"
    case _: TypesafeException.Authentication       => "Authentication"
    case _: TypesafeException.PermissionDenied     => "PermissionDenied"
    case _: TypesafeException.NotFound             => "NotFound"
    case _: TypesafeException.UnprocessableEntity  => "UnprocessableEntity"
    case _: TypesafeException.RateLimit            => "RateLimit"
    case _: TypesafeException.Overloaded           => "Overloaded"
    case _: TypesafeException.InternalServer       => "InternalServer"
    case _: TypesafeException.ResponseValidation   => "ResponseValidation"
    case _: TypesafeException.ConnectionFailed     => "ConnectionFailed"
    case _: TypesafeException.Timeout              => "Timeout"
    case _: TypesafeException.MissingAnswer        => "MissingAnswer"
    case _: TypesafeException.MissingCredential    => "MissingCredential"
    case _: TypesafeException.InvalidQuestion      => "InvalidQuestion"
    case _: TypesafeException.InvalidConfiguration => "InvalidConfiguration"
  }

  private val allMembers: List[TypesafeException] = List(
    TypesafeException.BadRequest(None, "d"),
    TypesafeException.Authentication(None, "d"),
    TypesafeException.PermissionDenied(None, "d"),
    TypesafeException.NotFound(None, "d"),
    TypesafeException.UnprocessableEntity(None, "d"),
    TypesafeException.RateLimit(None, None, "d"),
    TypesafeException.Overloaded(None, "d"),
    TypesafeException.InternalServer(500, None, "d"),
    TypesafeException.ResponseValidation(None, "a.b", "d"),
    TypesafeException.ConnectionFailed(new RuntimeException("d")),
    TypesafeException.Timeout(5.seconds),
    TypesafeException.MissingAnswer("q1"),
    TypesafeException.MissingCredential("TYPESAFE_API_KEY"),
    TypesafeException.InvalidQuestion(Some("q1"), "d"),
    TypesafeException.InvalidConfiguration("TYPESAFE_LOG_LEVEL", "d")
  )

  test("distinguishing every member suffices") {
    allMembers.foreach(m => assertEquals(memberName(m), m.getClass.getSimpleName))
    // spec: question-model — InvalidQuestion joined the family (local refusal
    // of a limit-breaking question at submission): 13 -> 14
    // spec: client-configuration — InvalidConfiguration joined the family
    // (an unusable environment value fails resolution naming the variable):
    // 14 -> 15
    assertEquals(allMembers.map(memberName).distinct.size, 15)
  }

  // spec: error-model — Scenario: A failure still behaves as an ordinary failure
  test("a failure still behaves as an ordinary failure") {
    allMembers.foreach { m =>
      val ordinary: Exception = m // type-level: every member is an ordinary exception
      assert(ordinary.getMessage != null && !ordinary.getMessage.isBlank, s"$m has no readable description")
    }
  }

  // --------------------------------------------------------------------------
  // Requirement: Each documented refusal is its own member
  // --------------------------------------------------------------------------

  // spec: error-model — Property: Every documented refusal maps to exactly one member
  property("every-documented-refusal-maps-to-one-member") {
    forAll(genRefusal) { case (refusal, headers, body) =>
      val member = TypesafeException.fromResponse(refusal.status, headers, body)
      classify(true, refusal.kind)(memberName(member) == refusal.member)
    }
  }

  // spec: error-model — Property: Every documented refusal maps to exactly one member (injectivity)
  test("no two documented refusal classes map to the same member") {
    val distinctStatuses = List(400, 401, 403, 404, 422, 429, 529, 500)
    val members          = distinctStatuses.map(s => memberName(TypesafeException.fromResponse(s, Nil, "")))
    assertEquals(members.distinct.size, distinctStatuses.size)
  }

  // spec: error-model — Scenario: A refusal the caller caused
  test("a refusal the caller caused") {
    assertEquals(memberName(TypesafeException.fromResponse(400, Nil, "bad")), "BadRequest")
    assertEquals(memberName(TypesafeException.fromResponse(401, Nil, "bad")), "Authentication")
    assertEquals(memberName(TypesafeException.fromResponse(403, Nil, "bad")), "PermissionDenied")
    assertEquals(memberName(TypesafeException.fromResponse(404, Nil, "bad")), "NotFound")
    assertEquals(memberName(TypesafeException.fromResponse(422, Nil, "bad")), "UnprocessableEntity")
  }

  // spec: error-model — Scenario: Too many requests
  test("too many requests") {
    val member = TypesafeException.fromResponse(429, Nil, "slow down")
    member match {
      case r: TypesafeException.RateLimit => assertEquals(r.retryAfter, None)
      case other                          => fail(s"expected RateLimit, got $other")
    }
  }

  // spec: error-model — Scenario: Too many requests — the service-named delay is carried, when named
  property("rate-limit-carries-the-service-named-delay-or-none") {
    forAll(genRetryAfterCase) { case (delayHeaders, expected) =>
      TypesafeException.fromResponse(429, delayHeaders, "slow down") match {
        case r: TypesafeException.RateLimit => r.retryAfter == expected
        case _                              => false
      }
    }
  }

  // spec: error-model — Scenario: Overload is told apart from other service faults
  test("overload is told apart from other service faults") {
    val overloaded = TypesafeException.fromResponse(529, Nil, "busy")
    val general    = TypesafeException.fromResponse(503, Nil, "dead")
    assert(overloaded.isInstanceOf[TypesafeException.Overloaded], s"529 mapped to $overloaded")
    assert(general.isInstanceOf[TypesafeException.InternalServer], s"503 mapped to $general")
    assertNotEquals(memberName(overloaded), memberName(general))
  }

  // spec: error-model — Scenario: A general service fault
  test("a general service fault carries what the service reported") {
    TypesafeException.fromResponse(503, Nil, "the reported body") match {
      case i: TypesafeException.InternalServer =>
        assertEquals(i.status, 503)
        assertEquals(i.detail, "the reported body")
      case other                               => fail(s"expected InternalServer, got $other")
    }
  }

  // spec: error-model — undocumented refusals still carry what the service reported
  test("an undescribed refusal lands in the general member carrying its status") {
    TypesafeException.fromResponse(408, Nil, "timed out server-side") match {
      case i: TypesafeException.InternalServer => assertEquals(i.status, 408)
      case other                               => fail(s"expected InternalServer, got $other")
    }
    TypesafeException.fromResponse(418, Nil, "teapot") match {
      case i: TypesafeException.InternalServer => assertEquals(i.status, 418)
      case other                               => fail(s"expected InternalServer, got $other")
    }
  }

  // spec: error-model — Requirement: Every failure belongs to one closed family
  // (Ring 8): a status that is not a refusal is rejected, never mapped to a member
  test("a status that is not a refusal is rejected, not mapped") {
    intercept[IllegalArgumentException](TypesafeException.fromResponse(200, Nil, "ok"))
    intercept[IllegalArgumentException](TypesafeException.fromResponse(301, Nil, "moved"))
  }

  // --------------------------------------------------------------------------
  // Requirement: A failure to reach the service is told apart from a refusal by it
  // --------------------------------------------------------------------------

  // spec: error-model — Scenario: The service cannot be reached
  test("the service cannot be reached") {
    val cause  = new RuntimeException("connection refused")
    val member = TypesafeException.ConnectionFailed(cause)
    assertEquals(member.cause, cause)
    assertEquals(member.requestId, None)
    assert(member.isInstanceOf[TypesafeException])
  }

  // spec: error-model — Scenario: An attempt runs out of time
  test("an attempt runs out of time") {
    val member = TypesafeException.Timeout(5.seconds)
    assertEquals(member.limit, 5.seconds)
    assertEquals(member.requestId, None)
    assertEquals(memberName(member), "Timeout")
  }

  // spec: error-model — Requirement: unreachable and timeout are different members
  property("unreachable-is-not-timeout") {
    forAll(genLimit, genCause) { (limit, cause) =>
      val timeout     = TypesafeException.Timeout(limit)
      val unreachable = TypesafeException.ConnectionFailed(cause)
      timeout.limit == limit &&
        unreachable.cause == cause &&
        memberName(timeout) != memberName(unreachable) &&
        timeout.requestId == None && unreachable.requestId == None
    }
  }

  // --------------------------------------------------------------------------
  // Requirement: A failure carries the trace the service provided
  // --------------------------------------------------------------------------

  // spec: error-model — Property: A trace is carried through unchanged or reported absent
  // (refusal side; the success row is deferred to question-model's AnswerSet — Gate-0 decision)
  property("trace-is-carried-or-absent") {
    forAll(genRefusal, genTraceCase) { case ((refusal, headers, body), sent) =>
      val withTrace = sent.fold(headers)(v => ("x-typesafe-request-id", v) :: headers)
      val member    = TypesafeException.fromResponse(refusal.status, withTrace, body)
      val expected  = sent.flatMap(RequestId.fromHeader)
      member.requestId == expected
    }
  }

  // spec: error-model — Scenario: A refusal carrying a trace
  test("a refusal carrying a trace") {
    val member = TypesafeException.fromResponse(400, List("x-typesafe-request-id" -> "req-123"), "bad")
    assertEquals(member.requestId, RequestId.fromHeader("req-123"))
  }

  // spec: error-model — Scenario: A refusal carrying no trace
  test("a refusal carrying no trace reports it absent — never blank, never invented") {
    assertEquals(TypesafeException.fromResponse(400, Nil, "bad").requestId, None)
    assertEquals(TypesafeException.fromResponse(400, List("x-typesafe-request-id" -> ""), "bad").requestId, None)
    assertEquals(TypesafeException.fromResponse(400, List("x-typesafe-request-id" -> "   "), "bad").requestId, None)
  }

  // spec: error-model — the trace header name is HTTP; lookup is case-insensitive
  test("the trace header is read case-insensitively") {
    val member = TypesafeException.fromResponse(500, List("X-Typesafe-Request-Id" -> "req-9"), "dead")
    assertEquals(member.requestId, RequestId.fromHeader("req-9"))
  }

  // spec: error-model — the trace is carried through UNCHANGED: a non-blank
  // header value IS the reported trace, verbatim — asserted one-sided so a
  // blank-check inversion cannot hide behind the helper
  test("a non-blank trace is reported verbatim") {
    assertEquals(RequestId.fromHeader("req-9").map(_.value), Some("req-9"))
  }

  // --------------------------------------------------------------------------
  // Requirement: What can be known without asking is failed without asking
  // --------------------------------------------------------------------------

  // spec: error-model — Scenarios: No credential can be resolved / Reading an
  // answer that was never asked. The no-request proofs land with the producing
  // paths (specs 7 and 3 — Gate-0 decision); here the members exist in the
  // closed family and name what they must name.
  test("local failure members carry the name the caller needs") {
    val missing = TypesafeException.MissingAnswer("qTotal")
    assertEquals(missing.name, "qTotal")
    assertEquals(missing.requestId, None)
    assert(missing.getMessage.contains("qTotal"), "the failure names the name read")

    val credential = TypesafeException.MissingCredential("TYPESAFE_API_KEY")
    assertEquals(credential.envVar, "TYPESAFE_API_KEY")
    assertEquals(credential.requestId, None)
    assert(credential.getMessage.contains("TYPESAFE_API_KEY"), "the failure names the environment variable to set")
  }
}
